### PR TITLE
Support kebab-case config deserialization

### LINKED ISSUE #315: Kebab-case ServiceDiscoveryConfiguration
So that we can used `ServiceDiscoveryConfiguration` with jackson 2.7- (since spark requires jackons 2.6.5).

### PR DESCRIPTION
**Pull request by jared2501**
Fixes #315.

This change is [Reviewable](https://reviewable.io/reviews/palantir/http-remoting/316)

### CODE REVIEW

**Comment by jared2501** [comment]
Hey @markelliot @uschi2000 - can you guys make sure you're happy with this method before I do this for all the other config classes. It's the best way that I could find.

**Comment by jared2501** [comment]
@markelliot mentioned that it looks reasonable offline so I went ahead and did rest of the services.

**Comment by uschi2000** [comment]
one typo, few nitpicks.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[service-config/src/main/java/com/palantir/remoting1/config/service/ProxyConfiguration.java, line 35 at r1](https://reviewable.io:443/reviews/palantir/http-remoting/316#-Ka54TXP-_oUIwFErqSL:-Ka54TXP-_oUIwFErqSM:b-35duss) ([raw file](https://github.com/palantir/http-remoting/blob/5f3eaa15673d074c28e20684a5a813bfba4bf98d/service-config/src/main/java/com/palantir/remoting1/config/service/ProxyConfiguration.java#L35)):*
> ```Java
> @Immutable
> @JsonDeserialize(builder = ProxyConfiguration.Builder.class)
> @JsonSerialize(as = ImmutableProxyConfiguration.class)
> ```

Can you add serialization support in a separate commit so the kebabCase one is easier to revert at some point?

---

*[service-config/src/test/java/com/palantir/remoting1/config/service/ServiceConfigurationTest.java, line 45 at r1](https://reviewable.io:443/reviews/palantir/http-remoting/316#-Ka55KyguMeCiJdqn42J:-Ka55KyguMeCiJdqn42K:b-dt5n26) ([raw file](https://github.com/palantir/http-remoting/blob/5f3eaa15673d074c28e20684a5a813bfba4bf98d/service-config/src/test/java/com/palantir/remoting1/config/service/ServiceConfigurationTest.java#L45)):*
> ```Java
>                 + "\"connectTimeout\":\"1 day\",\"readTimeout\":\"1 day\",\"writeTimeout\":\"1 day\","
>                 + "\"uris\":[\"uri1\"],\"proxyConfiguration\":{\"hostAndPort\":\"host:80\",\"credentials\":null}}";
>         String deserializedKebabCase = "{\"api-token\":\"bearerToken\",\"security\":"
> ```

not 100% how to do this, but maybe this is simpler with https://github.com/google/guava/wiki/StringsExplained#caseformat ?
for instance, could serialize into a Map<String, Object>, then apply case format, or similar? this would apply to all tests. (not sure if it's worth it, your call)

---

*[ssl-config/src/main/java/com/palantir/remoting1/config/ssl/SslConfiguration.java, line 95 at r1](https://reviewable.io:443/reviews/palantir/http-remoting/316#-Ka55cIDvcuiAZwlCpjR:-Ka55cIDvcuiAZwlCpjS:blbmjjj) ([raw file](https://github.com/palantir/http-remoting/blob/5f3eaa15673d074c28e20684a5a813bfba4bf98d/ssl-config/src/main/java/com/palantir/remoting1/config/ssl/SslConfiguration.java#L95)):*
> ```Java
> 
>         @JsonProperty("trust-store-path")
>         Builder trustStorePathKebabCaseKebabCase(Path trustStorePath) {
> ```

string-replace error? (similar below)

---

*[ssl-config/src/test/java/com/palantir/remoting1/config/ssl/SslConfigurationTest.java, line 68 at r1](https://reviewable.io:443/reviews/palantir/http-remoting/316#-Ka55ltI-gOv3bLDCTdN:-Ka55ltI-gOv3bLDCTdO:b-m7ge98) ([raw file](https://github.com/palantir/http-remoting/blob/5f3eaa15673d074c28e20684a5a813bfba4bf98d/ssl-config/src/test/java/com/palantir/remoting1/config/ssl/SslConfigurationTest.java#L68)):*
> ```Java
>                 .isEqualTo(serialized);
>     }
> ```

nit: remove \n

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/316#-:-Ka55xf7j5ec48pJgCaU:b-lt430q)*

**Comment by jared2501** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[service-config/src/main/java/com/palantir/remoting1/config/service/ProxyConfiguration.java, line 35 at r1](https://reviewable.io:443/reviews/palantir/http-remoting/316#-Ka54TXP-_oUIwFErqSL:-Ka578gT9WLLMsow3hBu:b-896fix) ([raw file](https://github.com/palantir/http-remoting/blob/5f3eaa15673d074c28e20684a5a813bfba4bf98d/service-config/src/main/java/com/palantir/remoting1/config/service/ProxyConfiguration.java#L35)):*
<details><summary><i>Previously, uschi2000 (Robert Fink) wrote…</i></summary><blockquote>

Can you add serialization support in a separate commit so the kebabCase one is easier to revert at some point?
</blockquote></details>

Done.

---

*[service-config/src/test/java/com/palantir/remoting1/config/service/ServiceConfigurationTest.java, line 45 at r1](https://reviewable.io:443/reviews/palantir/http-remoting/316#-Ka55KyguMeCiJdqn42J:-Ka56rmaeBzCaP5iTprt:bsqehqo) ([raw file](https://github.com/palantir/http-remoting/blob/5f3eaa15673d074c28e20684a5a813bfba4bf98d/service-config/src/test/java/com/palantir/remoting1/config/service/ServiceConfigurationTest.java#L45)):*
<details><summary><i>Previously, uschi2000 (Robert Fink) wrote…</i></summary><blockquote>

not 100% how to do this, but maybe this is simpler with https://github.com/google/guava/wiki/StringsExplained#caseformat ?
for instance, could serialize into a Map<String, Object>, then apply case format, or similar? this would apply to all tests. (not sure if it's worth it, your call)
</blockquote></details>

could be worth doing later, but don't have energy to do it tonight sorry

---

*[ssl-config/src/main/java/com/palantir/remoting1/config/ssl/SslConfiguration.java, line 95 at r1](https://reviewable.io:443/reviews/palantir/http-remoting/316#-Ka55cIDvcuiAZwlCpjR:-Ka5738BPDGWFkpNAVAn:b-60xcdc) ([raw file](https://github.com/palantir/http-remoting/blob/5f3eaa15673d074c28e20684a5a813bfba4bf98d/ssl-config/src/main/java/com/palantir/remoting1/config/ssl/SslConfiguration.java#L95)):*
<details><summary><i>Previously, uschi2000 (Robert Fink) wrote…</i></summary><blockquote>

string-replace error? (similar below)
</blockquote></details>

woops - done

---

*[ssl-config/src/test/java/com/palantir/remoting1/config/ssl/SslConfigurationTest.java, line 68 at r1](https://reviewable.io:443/reviews/palantir/http-remoting/316#-Ka55ltI-gOv3bLDCTdN:-Ka577bGPZvfdyR9jROB:b-896fix) ([raw file](https://github.com/palantir/http-remoting/blob/5f3eaa15673d074c28e20684a5a813bfba4bf98d/ssl-config/src/test/java/com/palantir/remoting1/config/ssl/SslConfigurationTest.java#L68)):*
<details><summary><i>Previously, uschi2000 (Robert Fink) wrote…</i></summary><blockquote>

nit: remove \n
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/316)*

**Comment by uschi2000** [comment]
just turned on building forks, should be building with next commit.

**Comment by uschi2000** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/316#-:-Ka59xQN0L4WPERLmtMX:bnfp4nl)*

**Review by uschi2000 — APPROVED** [review]

**Comment by uschi2000** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/316)*

**Comment by uschi2000** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/316)*

**Pull request merged**
