### PR TITLE
jaxrs-clients shadowJar does not contain ssl-config or service-config classes

### PR DESCRIPTION
**Pull request by uschi2000**
This once's nasty: we cannot include those classes since their jackson annotations get relocated. Any ideas, @pnepywoda @markelliot ?

### CODE REVIEW

**Comment by pnepywoda** [comment]
oh yeah man, yuck....well, the annotations should be fine to not shade right? no logic in those to conflict with other versions...

**Comment by uschi2000** [comment]
that's the hope.

**Comment by uschi2000** [comment]
ok, so turns out shading jackson is not really going to work :(

**Comment by uschi2000** [comment]
which also means that shading feign is non-trivial due to feign-jackson.

**Comment by markelliot** [comment]
what does "not really going to work" mean?

**Comment by uschi2000** [comment]
JsonSerializer contains this thing:

```
    /**
     * This marker class is only to be used with annotations, to
     * indicate that <b>no serializer is configured</b>.
     *<p>
     * Specifically, this class is to be used as the marker for
     * annotation {@link com.fasterxml.jackson.databind.annotation.JsonSerialize}.
     */
    public abstract static class None
        extends JsonSerializer<Object> { }
```

Thus:

```
java.lang.IllegalStateException: AnnotationIntrospector returned Class httpremoting.shaded.com.fasterxml.jackson.databind.JsonSerializer$None; expected Class<JsonSerializer>
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializerInstance(DefaultSerializerProvider.java:526)
    at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerFromAnnotation(BasicSerializerFactory.java:492)
    at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:134)
    at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1166)
    at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1120)
    at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:471)
    at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:669)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:107)
    at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3385)
    at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:2803)
    at com.palantir.atlasdb.persister.JacksonPersister.persistToBytes(JacksonPersister.java:51)
```

I could dig deeper, but I suspect it's a can of worms.

**Comment by markelliot** [comment]
Bummer. Back to special casing Jackson 2.4?

**Pull request closed without merging**
