### PR TITLE
Stop shading jaxrs-clients library

### LINKED ISSUE #443: Don't use shading in jaxrs-clients

### PR DESCRIPTION
**Pull request by uschi2000**
Fixes #443

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/http-remoting/451)

### CODE REVIEW

**Comment by uschi2000** [comment]
@gracew I'm going to run through the https://github.com/palantir/http-remoting/issues?q=is%3Aissue+is%3Aopen+label%3AFor-3.0.0 issues today and merge them into the for-3.0.0 branch. Would love to get your review.

**Comment by gracew** [comment]
cool. I won't have too much time today but can do a post-merge pass of the PRs tomorrow.

**Comment by gracew** [comment]
looks fine. why are we removing the shading though? is it b/c of the version bumps in #452 ?

**Comment by uschi2000** [comment]
The majority of consumers does not needed the shaded libraries. Those who
do can do the shading on the consumer side.

**Pull request merged**
