### PR TITLE
Enable wrapping a ScheduledExecutorService with a new trace for every execution

### PR DESCRIPTION
**Pull request by diogoholanda**

### CODE REVIEW

**Comment by diogoholanda** [comment]
@uschi2000 @bavardage

**Comment by bavardage** [comment]
only gotcha here, is if you wrapWithNewTrace a ScheduledExecutorService which is already wrapped with the other method (which may be common in a 'standard' way of constructing these) then it won't act as expected

**Comment by uschi2000** [comment]
diogo, can you add a java comment explaining ben's point? (this should be added to both wrapping functions.)

**Comment by diogoholanda** [comment]
Something like that? Let me know if you want to rephrase it

**Comment by bavardage** [comment]
nope, not like this - I think it happens the other way around.

The outer wrapping has no effect

**Comment by bavardage** [comment]
actually no, you're correct - don't mind me!

**Review by bavardage — APPROVED** [review]

**Review by uschi2000 — APPROVED** [review]

**Pull request merged**
