### PR TITLE
more fromClass fun

### PR DESCRIPTION
**Pull request by markelliot**
This change is [Reviewable](https://reviewable.io/reviews/palantir/http-remoting/390)

### CODE REVIEW

**Comment by markelliot** [comment]
@uschi2000

**Review by uschi2000 — APPROVED** [review]

**Review by uschi2000 — APPROVED** [review]

**Comment by ghost** [comment]
Hmm, if we deprecate the strict version and use the non-strict version this means that if your service doesn't contain the version in the manifest then the only way to catch this is by integration testing...

**Comment by ghost** [comment]
This is especially easy to mess up considering that the version is injected by a copy/pasted bit of gradle code we move around

**Comment by ghost** [comment]
I guess I can achieve my desired behaviour by doing:

```
UserAgents.fromClass(FooServer.class, null, null)
```

**Pull request merged**
