### PR TITLE
Upgrade feign to version 8.14.4

### PR DESCRIPTION
**Pull request by leeavital**

### CODE REVIEW

**Comment by schlosna** [comment]
Looking at https://github.com/Netflix/feign/blob/master/CHANGELOG.md this bumps OkHttp and Gson:

Version 8.14
- Add support for RxJava Observable and Single return types via the HystrixFeign builder.
- Adds fallback implementation configuration to the HystrixFeign builder
- Bumps dependency versions, most notably Gson 2.5 and OkHttp 2.7

Version 8.13
- Never expands >8kb responses into memory

Version 8.12
- Adds Feign.Builder.decode404() to reduce boilerplate for empty semantics.

Version 8.11
- Adds support for Hystrix via a HystrixFeign builder.

**Comment by nmiyake** [comment]
Don't think this should impact anything, but the next Feign release should be soon (the maintainer had actually told me it would be yesterday, but looks like they're a bit behind) and contains a PR that I merged that I'd like for http-remoting. Should be a minor bump so don't imagine it will be hard to bump again after this, but just wanted to mention it in case that affects when we want to do the bump in this library.

**Comment by leeavital** [comment]
@nmiyake  that's fine by us. This is easily patchable with gradle exclusions.

**Comment by uschi2000** [comment]
ok, let's wait for the next feign release.

**Comment by nmiyake** [comment]
I've opened PR #77 to upgrade to 8.15.0 (and fixes other dependencies and unit tests)

**Comment by nmiyake** [comment]
@uschi2000 or @markelliot , this can be closed since #77 merged.

**Comment by uschi2000** [comment]
Closing in lieu of #77

**Pull request closed without merging**
