### PR TITLE
Rfink/qos

### PR DESCRIPTION
**Pull request by uschi2000**

### CODE REVIEW

**Comment by uschi2000** [comment]
All of this has been individually reviewed in separate PRs. Want to merge this into develop now.

**Comment by j-baker** [comment]
+1. The individual PRs were fine. I'm not going to look at the whole because it's too much code.

**Comment by ellisjoe** [comment]
anything in particular you want another look at?

**Comment by uschi2000** [comment]
I don't think so, @ellisjoe .

**Comment by ellisjoe** [comment]
Cool. merge away

**Pull request merged**
