### PR TITLE
[improvement] Use new dispatcher per client

### LINKED ISSUE #860: Shared dispatcher is problematic for highly parallel clients
In #706 a change was made to use a single global dispatcher for all clients. However we did not increase the maximum number of simultaneous requests.

Because of this, it is very easy to inadvertently saturate the dispatcher and cause slowness in requests to _all_ services. The ability to further parallelize workloads is then limited because you must take great care not to saturate the dispatcher with requests to a single client. This is particularly troublesome when calling APIs that only expose a singular endpoint and expect clients to do the parallelization.

In general, it seems incorrect to queue requests globally. This makes it possible for high-volume low-importance (willing to tolerate being queued) requests to starve low-volume high-importance requests.

### PR DESCRIPTION
**Pull request by pkoenig10**
Fixes #860

### CODE REVIEW

**Comment by j-baker** [comment]
Why not just increase max concurrent calls significantly above max calls per host? Would be a less invasive change.

Sent from my iPhone

On Nov 2, 2018, at 22:08, Patrick Koenig <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixes #860 [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_palantir_conjure-2Djava-2Druntime_issues_860&d=DwMCaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=mzXajGbPp7kc5a_CRzXttisFRf8mEsV3gcMrXd3MRoc&m=-vwagiyAnMifavLtPJuX6NYNF88RE6EfZgypls-Ij-0&s=cy077ts-Qo-MP5fPKPzTrfYhVWrjttDTAYc3YFd-MkU&e=>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/palantir/conjure-java-runtime/pull/861 [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_palantir_conjure-2Djava-2Druntime_pull_861&d=DwMCaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=mzXajGbPp7kc5a_CRzXttisFRf8mEsV3gcMrXd3MRoc&m=-vwagiyAnMifavLtPJuX6NYNF88RE6EfZgypls-Ij-0&s=yEac1dTLb-QKhrmCKcsGrnVvLg17gxg04ZnEdvwaR14&e=>

Commit Summary

  *   Use new dispatcher per client

File Changes

  *   M okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/OkHttpClients.java [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_palantir_conjure-2Djava-2Druntime_pull_861_files-23diff-2D0&d=DwMCaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=mzXajGbPp7kc5a_CRzXttisFRf8mEsV3gcMrXd3MRoc&m=-vwagiyAnMifavLtPJuX6NYNF88RE6EfZgypls-Ij-0&s=dRNoVEtLLyGNf-3VD1BjcVe328oCcZIxRsZRAo6Af-s&e=> (53)

Patch Links:

  *   https://github.com/palantir/conjure-java-runtime/pull/861.patch [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_palantir_conjure-2Djava-2Druntime_pull_861.patch&d=DwMCaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=mzXajGbPp7kc5a_CRzXttisFRf8mEsV3gcMrXd3MRoc&m=-vwagiyAnMifavLtPJuX6NYNF88RE6EfZgypls-Ij-0&s=2HwIMW_SfjGGntWWBZrk2wxgYkAhl12niIHC0AEqLUE&e=>
  *   https://github.com/palantir/conjure-java-runtime/pull/861.diff [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_palantir_conjure-2Djava-2Druntime_pull_861.diff&d=DwMCaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=mzXajGbPp7kc5a_CRzXttisFRf8mEsV3gcMrXd3MRoc&m=-vwagiyAnMifavLtPJuX6NYNF88RE6EfZgypls-Ij-0&s=fJ7kJ7IBN_TprMM3GoLQ3Rnb0RKThiTPKH7XgKR8XDU&e=>

**Comment by pkoenig10** [comment]
The primary concern with have a single global dispatcher is that you are unable to use different requests queues when making requests in different contexts. This means that high volume requests can starve low volume requests.

<br>

For example suppose there are two code paths:
- A, which makes 1000 parallel requests (maybe an executor with a large thread pool)
- B, which makes a single request

It becomes very easy to starve threads on code path B. In reality you likely want a fairer, less greedy distribution of resources (e.x. A gets 95% and B gets 5%).

<br>

Simply increasing the max concurrent calls has two downsides:
- It's still a well-hidden limit that can cause widespread performance issues if exceeded
- It doesn't actually solve the distribution-of-resources problem

**Comment by j-baker** [comment]
Then I'd recommend we set a concurrency limit per-endpoint using our ConcurrencyLimiters (where this is configurable).

**Comment by pkoenig10** [comment]
I don't think that will work here since the concurrency limiter is an interceptor. So we won't hit the limiter until our request is actually being run.

Unless maybe you're suggesting we move the limiter to when enqueue the requests?

**Comment by j-baker** [comment]
Yes, but... In that case why have a limit on the dispatcher at all.
Can we sync up tomorrow please?
Wanna get to the point where we're on the same page, hard to iterate over GitHub.

Sent from my iPhone

On Nov 6, 2018, at 23:47, Patrick Koenig <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't think that will work here since the concurrency limiter is an interceptor. So we won't hit the limiter until our request is actually being run.

Unless maybe you're suggesting we move the limiter to when enqueue the requests?

**Pull request closed without merging**
