### PR TITLE
Add support for Java 8 primitive optionals

### PR DESCRIPTION
**Pull request by markelliot**
This change is [Reviewable](https://reviewable.io/reviews/palantir/http-remoting/376)

### CODE REVIEW

**Review by uschi2000 — APPROVED** [review]
Wow, that's tedious. Tried very hard to find a typo, but didn't manage to spot one.

**Comment by uschi2000** [comment]
It's a lot of code to avoid boxing/unboxing. Can't judge if it's worth it :/

**Comment by markelliot** [comment]
Yep, it's mostly boilerplate. We could probably use Jackson to coerce everything that's a PathParam or HeaderParam that's not already a string, but since that wasn't how we were already doing this I did the tedious repetition thing.

I suspect better to support these things than not, but likely worth a discussion about code and test quality of the whole project.

Also, latest Dropwizard already has all the Jersey stuff by default, we may want to split that stuff out so that Dropwizard 1+ users do not double install.

For good measure, I did also check to see if we could depend on dropwizard-jersey, but it unfortunately has a long dependency tree, including Jackson, which is a persistent issue for us when trying to run servers that talk to Spark.

On Mar 17, 2017, at 4:34 AM, Robert Fink <notifications@github.com<mailto:notifications@github.com>> wrote:


It's a lot of code to avoid boxing/unboxing. Can't judge if it's worth it :/

**Comment by uschi2000** [comment]
Half of this will go away when we remove jaxrs-clients, and yeah, definitely agree the code&test quality needs some love here. Anyway, +1 for this PR.

**Pull request merged**
