### PR TITLE
Rfink/update plugins

### PR DESCRIPTION
**Pull request by uschi2000**

### CODE REVIEW

**Comment by uschi2000** [comment]
New baseline config as per `gradlew updateBaselineConfig`

**Comment by uschi2000** [comment]
@markelliot

**Comment by markelliot** [comment]
:+1:

**Comment by nmiyake** [comment]
+1, verified that this fixes the Checkstyle errors.

I still see FindBugs warnings in the generated files, but those are less important since they aren't errors. Will change my other PR to only include FindBugs change and that can be discussed there.

**Comment by uschi2000** [comment]
rebasing

**Pull request merged**
