### PR TITLE
Add ServiceUrls

### PR DESCRIPTION
**Pull request by leeavital**

### CODE REVIEW

**Comment by leeavital** [comment]
@pnepywoda @ashwinr

**Comment by qinfchen** [comment]
FYI,  I was trying to add this before and we concluded that http-remoting may not be best place for serviceUrls , as there is no internal/external concept on the client side.

**Comment by markelliot** [comment]
Yep, not sure http-clients wants an API of more than Set<String> for URLs.

**Comment by uschi2000** [comment]
What's the motivation for this? (Sorry, I may have missed some conversation)

**Comment by pnepywoda** [comment]
Compass was about to put a ServiceUrl's class in their compass-client and I
pointed out that I didn't think anything more should be added to
compass-client - it should be removed as much as possible (note how we're
also trying to remove our foundry-clients)

**Comment by markelliot** [comment]
thoughts on just adding another project here called 'service-config' and putting it in there? This class is not an http-client concern.

**Comment by qinfchen** [comment]
Would the highline library i am currently working on be the right place for that? since it focuses on app/bundle configuration, i was planning on adding a highline-urls or config for that

**Comment by markelliot** [comment]
sure, is that something you're planning on making an OSS contrib?

**Comment by qinfchen** [comment]
Yes, that is the plan.

**Comment by leeavital** [comment]
@rob Set<String> won't always suffice. For example, we need to configure
urls that are accessible both by internal host and by public DNS.

**Comment by rob** [comment]
Thanks @leeavital

**Comment by markelliot** [comment]
Given that @qinfchen is going to open source this elsewhere, going to close this out.

**Pull request closed without merging**
