### PR TITLE
Add ability to specify keystore for SSLSocketFactory

### PR DESCRIPTION
**Pull request by nmiyake**
Motivation is to add the ability to leverage this library when making TLS connections that require client certificates. In these situations, both a key store and a trust store need to be specified separately. Verified this with Axiom -- can't establish a connection with custom keys/trust before this change, but can do so after.

This isn't ready to merge as-is, but wanted to submit for feedback before I work on it any further.

My own thoughts:
- Naming of `TrustStoreConfiguration` makes it slightly awkward to use for key store as well, but this code would be exactly the same, so don't think that duplicating it wholesale as `KeyStoreConfiguration` makes much sense.
  - Could rename to something like `StoreConfiguration`, but would be a backcompat-break
- Similar for entire package/project -- named `trust-stores` and `trust`.
- Currently only added one more factory method with 2 optionals. Mirroring all of the methods for trust would make it too verbose.
- Could over-haul the approach completely and write `TrustStores` as a builder instead (where trust and key config can be set as parameters) to avoid factory method combinatorics issues, but that would be a major change so didn't want to do it without checking first.

### CODE REVIEW

**Comment by markelliot** [comment]
Awesome, thanks. Have this tagged as #22 :)

In terms of impl: I think it might make more sense for TrustStoreConfiguration to collect the keyStore, path and password and for there still to be a single factory. 

The class and project name probably ought to change, though Java annoyingly calls these things "key stores", and per your comments, not really sure what a better name would be. This whole thing is in service of making an SSLSocketFactory, so maybe we can go with "ssl-config" and "SslConfiguration"?

**Comment by uschi2000** [comment]
+1 for single factory

since we will rely on this to establish a 2-way trusted channel, it would be imported to have integration tests verifying that connections succeed/fail depending on the configured trust setup

**Comment by nmiyake** [comment]
OK great, thanks for the feedback! I'll change the config to collect everything, give a first stab at naming, add some tests and put back up.

**Comment by nmiyake** [comment]
I think I messed this up by force-pushing on my branch instead of adding a commit. Closing and re-opening.

**Pull request closed without merging**
