### PR TITLE
bump okhttp version to 2.7.5

### PR DESCRIPTION
**Pull request by jmcampanini**
for motivation: https://corner.squareup.com/2016/03/certificate-pinner-vulnerability.html

related: https://github.com/palantir/http-remoting/issues/83

### CODE REVIEW

**Comment by uschi2000** [comment]
@pnepywoda @mingyukim do you know of any spark-related incompatibilities with okhttp > 2.5.0?

**Comment by mingyukim** [comment]
Not okhttp particularly, but there could be from transitive dependencies? Here's the full list from Spark. https://github.com/apache/spark/blob/master/dev/deps/spark-deps-hadoop-2.6

**Comment by pnepywoda** [comment]
ping - do we still care to upgrade the okhttp version? What are the benefits of upgrading?

**Comment by jmcampanini** [comment]
sorry this fell off my radar. there was a security issue (linked in the first comment). up to you guys if you want to take it

**Pull request merged**
