### PR TITLE
Built-in http/2 support

### PR DESCRIPTION
**Pull request by markelliot**
This change is [Reviewable](https://reviewable.io/reviews/palantir/http-remoting/368)

### CODE REVIEW

**Comment by uschi2000** [comment]
lgtm. http1 users may suffer a perf penalty due to the added GCM cipher. should we make that clear in readme/release-notes?

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/368#-:-KenbBtER7p6nXT3cIib:b-rs6p5i)*

**Comment by markelliot** [comment]
Yeah…though we're also not providing any recourse. =/

**Comment by markelliot** [comment]
I suppose we could add something to explicitly enableH2CompatibleCiphers or something to the builders?

**Comment by uschi2000** [comment]
That would be effectively equivalent to `.enableHttp2()` for most http2
servers, right? I.e., clients would not support http2 out of the box.

**Comment by markelliot** [comment]
I tested with a few public websites (Google, Akamai, Cloudflare), and all of them seem to support a negotiation that does not contain the GCM cipher, and so are generally more liberal than the spec.

**Comment by uschi2000** [comment]
:lgtm:

---

Reviewed 10 of 12 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/368#-:-KenxBQBkZLgjzEsGMhU:bnfp4nl)*

**Comment by markelliot** [comment]
@uschi2000 need a GH approval to merge this

**Review by ashrayjain — APPROVED** [review]
in lieu of @uschi2000 :)

EDIT: ok, so that doesn't work...

**Review by uschi2000 — APPROVED** [review]

**Pull request merged**
