### PR TITLE
Upgrade to http-remoting-api 1.9.0

### PR DESCRIPTION
**Pull request by schlosna**
Pick up fixes in 1.8.0 and 1.9.0 from https://github.com/palantir/http-remoting-api/releases

* Fix NPE when serializing Arg with null value (https://github.com/palantir/http-remoting-api/pull/73)
* Simplified assertions on ServiceException args, and more helpful error messages (https://github.com/palantir/http-remoting-api/pull/71)
* ServiceConfiguration timeouts can now be configured with sub-second granularity (https://github.com/palantir/http-remoting-api/pull/75)
* new UnknownRemoteException with status & body fields (https://github.com/palantir/http-remoting-api/pull/91)

### CODE REVIEW

**Comment by iamdanfox** [comment]
@schlosna could run `./gradlew generateLock saveLock` to re-generate those cheeky lock files please?

**Comment by schlosna** [comment]
@iamdanfox will have to do that when I'm back on my machine

**Comment by schlosna** [comment]
hey @iamdanfox , dependency locks are updated

**Review by qinfchen — APPROVED** [review]

**Comment by iamdanfox** [comment]
fixes https://github.com/palantir/http-remoting-api/issues/66

**Pull request merged**
