### PR TITLE
support initializing a trace with explicit sampling

### PR DESCRIPTION
**Pull request by bavardage**
cc @padamowicz

### CODE REVIEW

**Comment by bavardage** [comment]
(did in gh-ui, will see if I need to change tests.. :P)

**Review by uschi2000 — CHANGES_REQUESTED** [review]
sorry to be a gh ui party pooper, but can you add a test for this behavior, please?

**Comment by bavardage** [comment]
haha yeah sure

**Review by uschi2000 — APPROVED** [review]

**Comment by bavardage** [comment]
added a test, but this stuff seems fiddly to test...

**Pull request merged**
