### PR TITLE
circle.yml: always use Gradle daemon and parallelism

### PR DESCRIPTION
**Pull request by uschi2000**

### CODE REVIEW

**Comment by uschi2000** [comment]
this doesn't make any sense to me :(

**Comment by markelliot** [comment]
not sure why you're daemonizing, what's not making sense?

**Comment by uschi2000** [comment]
build still fails randomly

**Comment by markelliot** [comment]
Can we open an issue on the forums?

Sent from my iPhone

On Jul 21, 2016, at 12:28 AM, Robert Fink <notifications@github.com<mailto:notifications@github.com>> wrote:

build still fails randomly

**Comment by uschi2000** [comment]
Yep, can do. Looks like disabling --daemon helps for now.

**Pull request closed without merging**
