### PR TITLE
Bring back old exception message

### PR DESCRIPTION
**Pull request by ellisjoe**

### CODE REVIEW

**Comment by carterkozak** [comment]
I prefer this over the alternative, but I would prefer to avoid control flow based on exception message parsing. Too late in this case I suppose.

**Comment by carterkozak** [comment]
👍

**Comment by iamdanfox** [comment]
I've fixed up the internal product that was regexing exception messages.

**Comment by carterkozak** [comment]
Thanks Dan!

**Comment by ellisjoe** [comment]
fixed this in the client lib

**Pull request closed without merging**
