### PR TITLE
Refactor jaxrs client API

### PR DESCRIPTION
**Pull request by uschi2000**

### CODE REVIEW

**Comment by uschi2000** [comment]
Alternative API for jaxrs clients. Note that JaxRsClientConfig is (1) completely independent from jaxrs (and could be reused for retrofit2 clients), (2) an adapter for ServiceConfiguration that makes fewer assumptions on things being located on disk. Thoughts, @markelliot

**Comment by markelliot** [comment]
This is fine; I was thinking you could also just mirror the Client/ClientBuilder class setup for retrofit2.

**Comment by uschi2000** [comment]
Yep, that was my plan. Do you think the config/clientbuilder will diverge
between jaxrs-type and retrofit-type clients?
  R.

**Comment by markelliot** [comment]
Nope, should be the same, I think. It's desirable for it to be the same, at least.

**Comment by uschi2000** [comment]
Agree.

**Comment by uschi2000** [comment]
Circle down?

**Pull request merged**
