### PR TITLE
remove jackson 2.4 compat

### PR DESCRIPTION
**Pull request by robert3005**
It was here only for spark compatibility. Spark 2.0 is on jackson 2.6.5 so we don't need special handling.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/http-remoting/195)

### CODE REVIEW

**Comment by uschi2000** [comment]
I don't think we can upgrade this before a bunch of services relying on Spark have removed Spark 1.x support.

**Comment by robert3005** [comment]
I will make sure services get migrated to 2.0 ASAP (probably this week). Can we merge this after you cut 1.0?

**Comment by uschi2000** [comment]
I think we need to keep 2.4 Support in here for a little while so that
teams can take updates without the spark blocker.

**Comment by uschi2000** [comment]
any update here, Rob?

**Comment by robert3005** [comment]
We shouldn't need 2.4 support anymore. I believe nothing internally uses it anymore and otherwise don't see good reason to support it.

**Comment by schlosna** [comment]
Ping on this as it would be nice to remove Jackson 2.4 support, though I guess we have to wait until 2.0?

**Comment by uschi2000** [comment]
Yep. Is this hurting anyone as it is?

**Comment by schlosna** [comment]
I don't know of it hurting anyone, but there are compatibility issues with Jackson Afterburner on 2.4 so we don't enable it, see https://github.com/palantir/http-remoting/pull/284/files#diff-01d6c75da22a1a001eb7a8e0e3198989R36

**Comment by markelliot** [comment]
we solved this by providing the missing 2.4 feature we needed as s shim

**Pull request closed without merging**
