### PR TITLE
Safer defaults for ObjectMappers

### PR DESCRIPTION
**Pull request by markelliot**
This change is [Reviewable](https://reviewable.io/reviews/palantir/http-remoting/363)

### CODE REVIEW

**Comment by uschi2000** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[extras/jackson-support/src/main/java/com/palantir/remoting2/ext/jackson/ObjectMappers.java, line 44 at r1](https://reviewable.io:443/reviews/palantir/http-remoting/363#-KeLe5_TdTG1H_iR3MA1:-KeLe5_TdTG1H_iR3MA2:beubv9k) ([raw file](https://github.com/palantir/http-remoting/blob/e2aafe3855c0fb39f7b4272d63c6105c9aaff704/extras/jackson-support/src/main/java/com/palantir/remoting2/ext/jackson/ObjectMappers.java#L44)):*
> ```Java
>                 .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
>                 .disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE)
>                 .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
> ```

so this is configuration for clients, right? as it stands, this object mapper isn't used for servers, i.e., in HttpRemotingJerseyFeature. any idea how to prevent people from doing the wrong this server-side?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/363)*

**Comment by markelliot** [comment]
That's right. We might consider changing the name here to "clientDefault" and also offering a serverDefault that people applying server object mappers can choose to use.

**Comment by markelliot** [comment]
...not a great way to force this with Jersey on the server, though.

**Review by uschi2000 — APPROVED** [review]

**Comment by uschi2000** [comment]
+1

**Pull request merged**
