### PR TITLE
Observers are identified by name in Tracer#subscribe

### PR DESCRIPTION
**Pull request by uschi2000**

### CODE REVIEW

**Comment by uschi2000** [comment]
Thoughts on this, @markelliot ? Goal is to make sure different observers don't trample each other.

**Comment by uschi2000** [comment]
Or maybe exactly is desired? I don't know.

**Comment by markelliot** [comment]
how does this make it more likely observers won't trample each other?

**Comment by uschi2000** [comment]
my explanation was the opposite of what I had in mind: this makes it so that trampling must be explicit. if your library registers an "SLF4J" observer and mine does too, then this will throw. i'm a little worried that we'll end with an unbounded number of similar observers if we dedupe them by object identity.

**Comment by markelliot** [comment]
Ok, agree this does that, though the namespacing is still unbounded, and it might be confusing to have your subscriber trampled, so we should probably add some logging if you trample but don't have object equivalence?

We can also say there's exactly one observer, and allow for a multi-observer observer that aggregates.

Practically speaking, I expect there to be ~2 observers max, ever.

**Comment by uschi2000** [comment]
the multi thing in itself doesn't quite help if someone else can come along
and replace it with something else.
i be down for (1) named observers, (2) "warn" log entry when you overwrite
an existing one (by name). deal?

**Comment by markelliot** [comment]
Yep, that's fine.

**Comment by markelliot** [comment]
Probably also want to warn any time size of the map grows to > 5, too.

**Review by markelliot — APPROVED** [review]

**Pull request merged**
