### PR TITLE
Disallow PathParam Optionals

### PR DESCRIPTION
**Pull request by markelliot**

### CODE REVIEW

**Comment by markelliot** [comment]
@uschi2000

**Comment by pnepywoda** [comment]
+!

**Comment by punya** [comment]
Even though http-remoting is written in Java 7, many consumers will use it in Java 8 servers. Therefore it seems desirable to block the use of Java 8 Optional as well - it should be possible to do this by looking up the class reflectively by name.

**Comment by pnepywoda** [comment]
People aren't using this lib expecting java8 optional support.

**Pull request merged**
