### PR TITLE
User agent not forced

### PR DESCRIPTION
**Pull request by jamesthomp**
Bring back the old methods (marked as deprecated) to allow for diamond dependencies to get updated.

### CODE REVIEW

**Comment by markelliot** [comment]
what's an example of a diamond dependency where this hits us?

**Comment by uschi2000** [comment]
foundryfs & multipass-bundle

**Comment by markelliot** [comment]
I'm okay with this, but maybe as an alternative we should just make the FeignClients deprecated and move to FeignClients2 (or some less-grossly named thing?)

**Comment by jamesthomp** [comment]
I agree that it would be nice to depreciate the class and not have a bunch of methods be deprecated, but I also think that FeignClients2 (or any name) is pretty gross. I don't feel strongly (so I'm happy to make the change to FeignClients2) but I think the current set up is nicer.

**Comment by markelliot** [comment]
Either way, can live with this as is, too.

**Comment by uschi2000** [comment]
Yep, let's leave the deprecated methods.

**Pull request merged**
