### PR TITLE
Reuse shared Jackson ObjectMapper

### LINKED ISSUE #283: should re-use object mapper instances
https://github.com/palantir/http-remoting/blob/f0425ff800381cdd4f31c077e3bb99b576cbd543/jaxrs-clients/src/main/java/com/palantir/remoting1/jaxrs/FeignJaxRsClientBuilder.java#L74

### LINKED ISSUE #285: Jackson ObjectMappers should enable Afterburner module
The implicitly created Jackson `ObjectMapper`s created and used by http-remoting should enable the afterburner module, see https://github.com/FasterXML/jackson-module-afterburner 

Note that this was previously enabled via `io.dropwizard.jackson.Jackson#configure` when using a Dropwizard provided or created `ObjectMapper`.

### PR DESCRIPTION
**Pull request by schlosna**
Enable Jackson Afterburner module for ObjectMappers

Closes #283
Closes #285

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/http-remoting/284)

### CODE REVIEW

**Comment by schlosna** [comment]
@uschi2000 @markelliot for review

**Review by markelliot — COMMENTED** [review]
I'm fine with this. I'd prefer to have `ObjectMappers#GUAVA_JDK7`, but since ObjectMapper can't be made immutable, leaking the instance is likely bad.

Rob's choice on approval.

**Comment by uschi2000** [comment]
I'm fine with it as it stands, modulo two style nitpicks

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[jaxrs-clients/src/main/java/com/palantir/remoting1/jaxrs/feignimpl/ObjectMappers.java, line 34 at r2](https://reviewable.io:443/reviews/palantir/http-remoting/284#-KVQS0_bl0V3TK_NoYQr:-KVQS0_bl0V3TK_NoYQs:bqiney4) ([raw file](https://github.com/palantir/http-remoting/blob/3cb2c74c8245917eaec82eecb8dd9dd40128ce35/jaxrs-clients/src/main/java/com/palantir/remoting1/jaxrs/feignimpl/ObjectMappers.java#L34)):_

> ``` Java
>     public static ObjectMapper guavaJdk7() {
>         // TODO: Replace this code with shading to support different versions of Jackson
>         ObjectMapper mapper = new ObjectMapper().registerModule(new GuavaModule());
> ```

```
= new Foo()
  .register(..)
  .register(..);
```

---

_[retrofit2-clients/src/main/java/com/palantir/remoting1/retrofit2/ObjectMappers.java, line 35 at r2](https://reviewable.io:443/reviews/palantir/http-remoting/284#-KVQSzXutfeW4MlCUiRh:-KVQSzXutfeW4MlCUiRi:bqiney4) ([raw file](https://github.com/palantir/http-remoting/blob/3cb2c74c8245917eaec82eecb8dd9dd40128ce35/retrofit2-clients/src/main/java/com/palantir/remoting1/retrofit2/ObjectMappers.java#L35)):_

> ``` Java
>         // TODO: Replace this code with shading to support different versions of Jackson
>         ObjectMapper mapper = new ObjectMapper().registerModule(new GuavaModule());
>         mapper.registerModule(new AfterburnerModule());
> ```

```
= new Foo()
  .register(..)
  .register(..);
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/284#-:-KVQTEPOZKaZD5ZF3ytT:b-spyra5)_

**Comment by uschi2000** [comment]
Reviewed 1 of 2 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/284)_

**Comment by schlosna** [comment]
Chained module registration

---

Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

_[jaxrs-clients/src/main/java/com/palantir/remoting1/jaxrs/feignimpl/ObjectMappers.java, line 34 at r2](https://reviewable.io:443/reviews/palantir/http-remoting/284#-KVQS0_bl0V3TK_NoYQr:-KVQV-UJddErtuaCsn_S:bb7f2mf) ([raw file](https://github.com/palantir/http-remoting/blob/3cb2c74c8245917eaec82eecb8dd9dd40128ce35/jaxrs-clients/src/main/java/com/palantir/remoting1/jaxrs/feignimpl/ObjectMappers.java#L34)):_
<details><summary>

<i>Previously, uschi2000 (Robert Fink) wrote…</i></summary>



> ```
> = new Foo()
>   .register(..)
>   .register(..);
> ```
> 
> </details>
> done

---

_[retrofit2-clients/src/main/java/com/palantir/remoting1/retrofit2/ObjectMappers.java, line 35 at r2](https://reviewable.io:443/reviews/palantir/http-remoting/284#-KVQSzXutfeW4MlCUiRh:-KVQUyQvx_Lb0GiEbSd9:bb7f2mf) ([raw file](https://github.com/palantir/http-remoting/blob/3cb2c74c8245917eaec82eecb8dd9dd40128ce35/retrofit2-clients/src/main/java/com/palantir/remoting1/retrofit2/ObjectMappers.java#L35)):_
<details><summary>

<i>Previously, uschi2000 (Robert Fink) wrote…</i></summary>



> ```
> = new Foo()
>   .register(..)
>   .register(..);
> ```
> 
> </details>
> done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/284#-:-KVQV12gV0PrAYw0uQhB:b-e5s1g8)_

**Comment by uschi2000** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/284)_

**Comment by uschi2000** [comment]
:lgtm:

---

Review status: 4 of 23 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/284#-:-KVQfgKM-ZKxnHOkHhbJ:bnfp4nl)_

**Comment by uschi2000** [comment]
Reviewed 19 of 19 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/284)_

**Pull request merged**
