### PR TITLE
Add method to merge service conf with discovery conf defaults

### PR DESCRIPTION
**Pull request by ellisjoe**
This change is [Reviewable](https://reviewable.io/reviews/palantir/http-remoting/289)

### CODE REVIEW

**Comment by ellisjoe** [comment]
@uschi2000

**Review by markelliot — APPROVED** [review]

**Comment by uschi2000** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[service-config/src/main/java/com/palantir/remoting1/config/service/ServiceDiscoveryConfiguration.java, line 96 at r1](https://reviewable.io:443/reviews/palantir/http-remoting/289#-KVkCSwnJcGUddoHcMyE:-KVkCSwnJcGUddoHcMyF:b-4nr773) ([raw file](https://github.com/palantir/http-remoting/blob/67ce2edb692ca92ffd51893a47725d851f0411f7/service-config/src/main/java/com/palantir/remoting1/config/service/ServiceDiscoveryConfiguration.java#L96)):_

> ``` Java
> 
>     /**
>      * Returns the {@link ServiceConfiguration} with missing properties populated with the properties found in this
> ```

"Returns a new {@link ServiceConfiguration} obtained by copying all values from the given configuration and then filling in absent optional values with defaults from this {@link ServiceDiscoveryConfiguration}."

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/289)_

**Comment by uschi2000** [comment]
One nitpick, otherwise :lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/289#-:-KVkCyEK56YB98P_6OFX:bjws9nr)_

**Comment by uschi2000** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/289)_

**Comment by ellisjoe** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[service-config/src/main/java/com/palantir/remoting1/config/service/ServiceDiscoveryConfiguration.java, line 96 at r1](https://reviewable.io:443/reviews/palantir/http-remoting/289#-KVkCSwnJcGUddoHcMyE:-KVkNY1_Hrj4guQLA9ZX:b-896fix) ([raw file](https://github.com/palantir/http-remoting/blob/67ce2edb692ca92ffd51893a47725d851f0411f7/service-config/src/main/java/com/palantir/remoting1/config/service/ServiceDiscoveryConfiguration.java#L96)):_
<details><summary>

<i>Previously, uschi2000 (Robert Fink) wrote…</i></summary>



> "Returns a new {@link ServiceConfiguration} obtained by copying all values from the given configuration and then filling in absent optional values with defaults from this {@link ServiceDiscoveryConfiguration}."
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/289)_

**Comment by uschi2000** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/289#-:-KVkOkjnYuMdE3QkBeQs:bnfp4nl)_

**Pull request merged**
