### PR TITLE
Rename http-clients to feign-clients

### PR DESCRIPTION
**Pull request by uschi2000**

### CODE REVIEW

**Comment by markelliot** [comment]
Hm, I wonder if it's reasonable to keep this as 'http-clients', ideally we're pushing a particular strategy.

**Comment by uschi2000** [comment]
where do you put retrofit things then? i'd like to avoid picking up
retrifit dependencies if all I want is a feign&okhttp client.

**Comment by markelliot** [comment]
One option: keep http-clients, add retrofit-clients.

Alternatively, I suppose we can state a strong preference for feign-clients in the README.

**Comment by markelliot** [comment]
Also, are we changing the published artifact name as a result of this?

**Comment by uschi2000** [comment]
Yep, all or nothing. I am happy to keep http-clients and add
retrofit-clients though.

**Pull request closed without merging**
