### PR TITLE
Upgrade Jackson to 2.12.1

### PR DESCRIPTION
**Pull request by carterkozak**
Revert "Fix: Downgrade Jackson to 2.11.1 (#1839)"

This reverts commit 588f920e4821123a3da6d70bbe8539a5d122effa.

## Before this PR
2.11.1

## After this PR
==COMMIT_MSG==
Upgrade Jackson to 2.12.1
==COMMIT_MSG==

## Possible downsides?
Jackson is important, changes may break things.

### CODE REVIEW

**Comment by jkozlowski** [comment]
What's the rollout here? Cut an RC and try it someplace? Or go for it and revert if issues are detected?

**Comment by carterkozak** [comment]
Planning to RC in order to get everything working in WC, then cut GA releases and release WC. There weren't many changes aside from the fixes we were tracking or contributed between 2.12.0 and 2.12.1, and most things worked fine on 2.12.0, so I'm not sure we'd get much out of an RC, and unfortunately this isn't the sort of thing we can feature-flag.

**Comment by jkozlowski** [comment]
Alright happy to approve, I can't think of anything other than actually cutting an RC, then finding a product team that would bump their dialogue dependency to test this out.

**Review by jkozlowski — APPROVED** [review]

**Comment by carterkozak** [comment]
:robot: :popcorn:

**Pull request merged**
