### PR TITLE
Upgrade Feign to version 8.15.0

### PR DESCRIPTION
**Pull request by nmiyake**

### CODE REVIEW

**Comment by nmiyake** [comment]
@uschi2000 @markelliot

**Comment by uschi2000** [comment]
cool! did any of the dependencies change?

**Comment by nmiyake** [comment]
Yes. Feign dependency changes are at https://github.com/Netflix/feign/commit/4f86d15dd88a07142f9179293858eba11d74f1f4.

Summary:
- okhttp: 2.5.0 -> 2.7.0
- gson: 2.3.1 -> 2.5
- mockwebserver: 2.5.0 -> 2.7.0
- jmh: 1.10.5 -> 1.11.2
- rxnetty: 0.4.11 -> 0.4.14
- rxjava: 1.0.13 -> 1.0.17
- netty-codec-http: 4.0.30.Final -> 4.1.0.Beta8
- maven-shade-plugin: 2.4.1 -> 2.4.2
- httpclient: 4.5 -> 4.5.1
- hystrix-core: 1.4.18 -> 1.4.21
- jackson-jaxrs-json-provider: 2.6.1 -> 2.6.4
- jackson-databind: 2.6.1 -> 2.6.4
- ribbon-loadbalancer: 2.1.0 -> 2.1.1
- slf4j-api: 1.7.12 -> 1.7.13
- slf4j-simple: 1.7.12 -> 1.7.13

On the http-remoting side, this required bumping mockwebserver to 2.7.0 to match Feign, and some of the unit tests that tested for failure cases had to be updated to check for new error messages ("Connection refused" changed to "Failed to connect")

**Comment by markelliot** [comment]
We should probably be blocking most of those deps.

**Comment by uschi2000** [comment]
what do you mean by blocking?

**Comment by nmiyake** [comment]
Same questions as Rob -- if you tell me what to mean/point me to an example, happy to update the PR to do so!

**Comment by markelliot** [comment]
I mean we should probably exclude some of those. Not sure we need ribbon/hystrix right now, for instance.

Sent from my iPhone

On Mar 5, 2016, at 9:29 AM, nmiyake <notifications@github.com<mailto:notifications@github.com>> wrote:

Same questions as Rob -- if you tell me what to mean/point me to an example, happy to update the PR to do so!

**Comment by uschi2000** [comment]
Sure, we can do that. It's somewhat orthogonal from this PR though. Happy
to merge this?

**Comment by markelliot** [comment]
So those are all existing deps?

**Comment by nmiyake** [comment]
Yes, those are all upgrades to existing deps (no new dependencies introduced in this upgrade)

**Comment by markelliot** [comment]
Cool, I'm good with merging then.

**Comment by uschi2000** [comment]
can you rebase/resolve, nick?

**Comment by nmiyake** [comment]
Done

**Pull request merged**
