### PR TITLE
Switch retrofit2-clients from using gson to jackson.

### PR DESCRIPTION
**Pull request by iamthomaspowell**

### CODE REVIEW

**Comment by markelliot** [comment]
@uschi2000, did you intentionally pick Gson over Jackson? Think we should've taken Jackson.

**Comment by uschi2000** [comment]
I don't actually remember who made the first retrofit client. If it was me, then it was not intentional.

**Comment by uschi2000** [comment]
Thomas, which Jackson version does this bring in?

**Comment by uschi2000** [comment]
In related news, I really need to change to nebula for dependencies so we have some accountability around library versions.

**Comment by iamthomaspowell** [comment]
This brings in Jackson 2.7.2. Seems that we explicitly specify 2.6.1 so I can force this version

**Comment by uschi2000** [comment]
No, that's fine. Thanks Thomas.

**Pull request merged**
