### PR TITLE
Introduce fromClassStrict and remove canDetectUserAgent

### PR DESCRIPTION
**Pull request by leeavital**
Addressing offline feedback from @markelliot

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/http-remoting/381)

### CODE REVIEW

**Review by markelliot — APPROVED** [review]

**Comment by pnepywoda** [comment]
@leeavital @markelliot 
This is a pretty annoying change - it means you can't startup whatever process uses `fromClassStrict` if it's not running from an already-built-jar....meaning you can't run it in your IDE :(

**Comment by markelliot** [comment]
Yep, this was the behavior Lee was looking for. Can certainly roll it back, or we can make it throw conditional on some debug system property.

**Comment by pnepywoda** [comment]
Lee, what's the rationale for disallowing running in an IDE?

**Comment by leeavital** [comment]
I had made this change https://github.com/palantir/sls-packaging/pull/207 to allow for running from gradle. That's how I usually run things, so I overlooked running from the IDE.

The idea was to get people to use the jar properties to get nice user agents, not to break IDE workflows.

We could do what @markelliot  suggesting add a `com.palantir.remoting.debug` property to suppress this, or we could just turn these exceptions into logs. 

I'm partial to logging because using a debug property would mean users need to mess with their launch configs and/or gradle configs

**Comment by uschi2000** [comment]
I like the logging idea.

**Comment by leeavital** [comment]
@pnepywoda looks like a workaround was added in #390

**Pull request merged**
